---
title: "Data analyses for Zhang & Wang et al. 2020, Plant & Soil submission"
author: "Rebecca Batstone"
date: "`r format(Sys.Date())`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

### Aims
Increases in anthropogenic nitrogen (N) deposition are expected to lead to an overall higher mean and lower variance of N in the soil, which may disproportionately affect leguminous plants that acquire N both symbiotically via rhizobia and abiotically from soil. Here, we investigate the effects of changing N-heterogeneity at a fine spatial scale on the legume-rhizobium symbiosis.

### Methods
We used a split-root system to introduce local soil N-heterogeneity, while maintaining the same overall plant-level amount of N. We treated root halves of five inbred lines of *Medicago truncatula* (HapMap lines 267, 270, 276, 279, and 313) with 50%–50%, 20%–80%, 10%–90%, or 2%–98% N and inoculated them with two *Ensifer meliloti* strains that differ in N-fixation ability.

### Results
Although shoot biomass was unaffected by N-heterogeneity, plant lines adjusted their relative investments in nodulation versus root proliferation to optimize N-acquisition; high-N root halves tended to invest more into root proliferation, while low-N root halves invested more into nodule formation. We detected hidden plasticity in partner choice: although all plants formed more nodules with the more effective N-fixing strain, roots experiencing greater N-limitation increased preference for effective N-fixing rhizobia. Furthermore, there was significant variation among plant lines in root proliferation and nodulation responses to N-heterogeneity.

### Conclusion
In response to N-heterogeneity, *M. truncatula* exhibited phenotypic plasticity in root proliferation, nodulation, and partner choice at the local half-root level. We suggest that plasticity in response to rhizosphere conditions makes legumes potentially resilient to changes in N-heterogeneity, particularly in a time of anthropogenic N deposition.

## Description of markdown (.md) files, relevant folders in parentheses:

1. data_prep:
    * import raw data (./raw_data/plant_info1.csv)
    * clean up datasets and save as .Rdata files (./prepped_data/)
  
2. models (saved lsmean files in ./models_files/):
    * Half root growth responses to N-hetergeneity
    * Half root nodulation responses to N-hetergeneity
    * Half root nodulation responses to N-hetergeneity, accounting for strain
    * Whole-plant trait analyses
    
3. figures (saved in ./figures_files):
    * Half root growth responses to N-hetergeneity (./figures_files/Fig_1)
    * Half root nodulation responses to N-hetergeneity (./figures_files/Fig_2)
    * Correlations btw root growth and nodulation (./figures_files/Fig_3)
    * Partner choice (./figures_files/Fig_4)
    * Whole-plant traits (./figures_files/Fig_S2)
    
4. reanalyses:
    * Import data from previous split-root experiment of Batstone *et al.* (2017) (./reanalyses_files/)
    * Models on traits in both rhizobia and fertilizer experiments
    * Figure to summarize trait responses (./figures_files/Fig_S1)
  
